name: Frontend S3 CI/CD

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/deploy-aws-s3.yml'

permissions:
  id-token: write
  contents: read

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        if: success()
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        if: success()
        run: |
          cd frontend
          npm install ci
      - name: Test
        if: success()
        run: |
          cd frontend
          npm run lint
          # npm run test
      - name: Build
        if: success()
        run: |
          cd frontend
          npm run build
      - name: Setup AWS credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: my-github-role-action

      - name: Deploy
        if: success()
        run: aws s3 sync ${{ secrets.FRONTEND_BUILD_PATH }} s3://${{ secrets.AWS_S3_NAME }} --delete

      - name: Print current branch
        run: echo ${{ secrets.GITHUB_REF }}
