name: Frontend S3 CI/CD

# on:
#   push:
#     branches: [ main ]
#     paths: 
#       - 'frontend/**'
#       - '.github/workflows/deploy-aws-s3.yml'

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/deploy-aws-s3.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'frontend/**'
      - '.github/workflows/deploy-aws-s3.yml'

permissions:
  id-token: write
  contents: read

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Gets branch on pull_request events
        if: github.event_name == 'pull_request'
        run: echo "##[set-output name=branch;]$(echo ${{ github.base_ref }})"
        id: pull_request_branch
          
      - name: Gets branch on push events
        if: github.event_name == 'push'
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: push_branch

      - name: Setup node
        if: success()
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        if: success()
        run: |
          cd frontend
          npm install ci

      - name: Test
        if: success()
        run: |
          cd frontend
          npm run lint
          # npm run test

      - name: Build
        if: success()
        run: |
          cd frontend
          npm run build

      - name: Setup AWS credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: my-github-role-action

      - name: Deploy
        if: success() && github.evet_name == 'push'
        run: |
          aws s3 sync ${{ secrets.FRONTEND_BUILD_PATH }} s3://${{ secrets.AWS_S3_NAME }} --delete
          echo "Actual branch - ${{ steps.push_branch.outputs.branch }}"

      
      # - name: Print Branch on push
      #   if: github.event_name == 'push'
      #   run: echo "Actual branch - ${{ steps.push_branch.outputs.branch }}"

      # - name: Print Branch on pull_request
      #   if: github.event_name == 'pull_request'
      #   run: echo "Actual branch - ${{ steps.pull_request_branch.outputs.branch }}"



