name: Deploy to aws s3

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: my-github-role-action

      - name: Deploy
        run: aws s3 sync ./dist/frontend s3://${{ secrets.AWS_S3_NAME }} --delete


