name: Deploy to aws s3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Setup AWS credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
      - run: npm ci

      - name: Build
      - run: npm build

      - name: Deploy
      - run: aws s3 sync ./dist/ng-github-actions-s3 s3://ng-github-actions-s3


